// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from '@prisma/config';

export default defineConfig({
  // Use the DIRECT_URL (port 5432) for migrations and pushing schemas.
  // This bypasses the connection pooler.
  datasource: {
    url: env('DIRECT_URL'),
  },
});
